// Temporary function to update locker assignments
export default async function updateLockerAssignments({ base44 }) {
  const lockerData = [
    ["Vestuario Femenino Planta Baja", "ELVIRA FERNANDEZ LARA", "1"],
    ["Vestuario Femenino Planta Baja", "ROSINA MOLINA MAÑODES", "2"],
    ["Vestuario Femenino Planta Baja", "NATALIA YAGUE", "3"],
    ["Vestuario Femenino Planta Baja", "GEMA CLEMENTE", "4"],
    ["Vestuario Femenino Planta Baja", "BEGOÑA HURTADO FERNANDEZ", "5"],
    ["Vestuario Femenino Planta Baja", "Mª ANGELES NUFRIO BUDIA", "6"],
    ["Vestuario Femenino Planta Baja", "CRISTINA TORREJON VALLADOLID", "7"],
    ["Vestuario Femenino Planta Baja", "TRINIDAD SANCHEZ M.RAMIRO", "8"],
    ["Vestuario Femenino Planta Baja", "ROSA GARCIA GARCIA", "9"],
    ["Vestuario Femenino Planta Baja", "SVETLANA ZAHARI RACHOVSCA", "10"],
    ["Vestuario Femenino Planta Baja", "ANA Mª HUERTA MUÑOZ", "11"],
    ["Vestuario Femenino Planta Baja", "Mª GEMA SANCHEZ SALOR", "12"],
    ["Vestuario Femenino Planta Baja", "ROSA Mª SANCHEZ SALOR", "13"],
    ["Vestuario Femenino Planta Baja", "MARIA JOSE GUTIERREZ BLANCO", "14"],
    ["Vestuario Femenino Planta Baja", "SVETLANA PETKOVA MARINOVA", "15"],
    ["Vestuario Femenino Planta Baja", "CRISTINA MIHUT SIDA", "16"],
    ["Vestuario Femenino Planta Baja", "ELISABETH RUIZ TELLEZ", "17"],
    ["Vestuario Femenino Planta Baja", "CARMEN LOPEZ GARCIA", "18"],
    ["Vestuario Femenino Planta Baja", "CRISTINA MARTINEZ LOPEZ", "19"],
    ["Vestuario Femenino Planta Baja", "TERESA BARRANCO ROMAN", "20"],
    ["Vestuario Femenino Planta Baja", "VANESA VASQUEZ GONZALEZ", "21"],
    ["Vestuario Femenino Planta Baja", "MARIA JOSE DELGADO", "22"],
    ["Vestuario Femenino Planta Baja", "MARIA MARTA GOMEZ VALVERDE", "23"],
    ["Vestuario Femenino Planta Baja", "VIORELA MAHALAGIU", "24"],
    ["Vestuario Femenino Planta Baja", "JENNIFER AMOROS", "25"],
    ["Vestuario Femenino Planta Baja", "SILVIA GOMEZ ARES", "26"],
    ["Vestuario Femenino Planta Baja", "ANA BELEN MIALDEA MARTINEZ", "27"],
    ["Vestuario Femenino Planta Baja", "PALOMA SANCHEZ GARCIA", "28"],
    ["Vestuario Femenino Planta Baja", "RAQUEL CARRION ALVAREZ", "29"],
    ["Vestuario Femenino Planta Baja", "ISABEL LOPEZ RODRIGUEZ", "30"],
    ["Vestuario Femenino Planta Baja", "ERIKA SANCHEZ", "31"],
    ["Vestuario Femenino Planta Baja", "NURIA DE LA RIVA DUARTE", "32"],
    ["Vestuario Femenino Planta Baja", "MARIA YUSTE CORBERA", "33"],
    ["Vestuario Femenino Planta Baja", "CARLA JARA", "34"],
    ["Vestuario Femenino Planta Baja", "SONIA BLASCO MARTIN", "35"],
    ["Vestuario Femenino Planta Baja", "TAMARA CEBALLOS ESTEVEZ", "36"],
    ["Vestuario Femenino Planta Baja", "MARIA DACIANA", "38"],
    ["Vestuario Femenino Planta Baja", "SUSANA MARTINEZ MARTINEZ", "39"],
    ["Vestuario Femenino Planta Baja", "EMILIA GOMEZ VALDES", "40"],
    ["Vestuario Femenino Planta Baja", "ROSA MARIA NAJERA", "41"],
    ["Vestuario Femenino Planta Baja", "SARA SANZ NAVARRO", "42"],
    ["Vestuario Femenino Planta Baja", "MARIA ISABEL PIRIS RIPADO", "43"],
    ["Vestuario Femenino Planta Baja", "ELENA HITA RUIZ", "44"],
    ["Vestuario Femenino Planta Baja", "GEMA MORENO CALERO", "45"],
    ["Vestuario Femenino Planta Baja", "GEMA PANIAGUA BARRIGA", "46"],
    ["Vestuario Femenino Planta Baja", "MARIA RECIO SABALL", "47"],
    ["Vestuario Femenino Planta Baja", "REVECA TERCHILA", "48"],
    ["Vestuario Femenino Planta Baja", "ROSALIA CASTAÑARES JIMENEZ", "49"],
    ["Vestuario Femenino Planta Baja", "PATRICIA GONZALEZ GARCIA", "50"],
    ["Vestuario Femenino Planta Baja", "EVA RUBIO", "51"],
    ["Vestuario Femenino Planta Baja", "PAOLA MARTINEZ RODRIGUEZ", "52"],
    ["Vestuario Femenino Planta Baja", "ESTHER GOMEZ SAEZ", "53"],
    ["Vestuario Femenino Planta Baja", "RAQUEL RODRIGUEZ TERCERO", "54"],
    ["Vestuario Femenino Planta Baja", "ESPERANZA RODRIGO FRANCISCO", "55"],
    ["Vestuario Femenino Planta Baja", "GEMA HERNANDEZ ELENA", "56"],
    ["Vestuario Femenino Planta Alta", "ADA SAEZ DEL CASTILLO", "101"],
    ["Vestuario Femenino Planta Alta", "IGMAR PRADO", "102"],
    ["Vestuario Femenino Planta Alta", "María del Valle Alcaide", "103"],
    ["Vestuario Femenino Planta Alta", "Dorina Lungu", "104"],
    ["Vestuario Femenino Planta Alta", "AMALIA ABELLAN CAÑIZARES", "105"],
    ["Vestuario Femenino Planta Alta", "ANA ISABEL PARDO DIAZ", "106"],
    ["Vestuario Femenino Planta Alta", "ANA BELEN ESCOBAR", "107"],
    ["Vestuario Femenino Planta Alta", "GÉNESIS MORENO", "108"],
    ["Vestuario Femenino Planta Alta", "ANA BELEN JIMENEZ CRIADO", "109"],
    ["Vestuario Femenino Planta Alta", "BRENDA JIMENEZ", "110"],
    ["Vestuario Femenino Planta Alta", "NATALIA OSYPETS", "111"],
    ["Vestuario Femenino Planta Alta", "Mª ÁNGELES FERNANDEZ JORDÁN", "112"],
    ["Vestuario Femenino Planta Alta", "ADORACION TOLEDANO TOLEDANO", "113"],
    ["Vestuario Femenino Planta Alta", "BEGOÑA TURUELO ARGUERA", "114"],
    ["Vestuario Femenino Planta Alta", "ASCENSION GARCIA PEREZ", "115"],
    ["Vestuario Femenino Planta Alta", "BELEN FERNANDEZ GARRIDO", "116"],
    ["Vestuario Femenino Planta Alta", "BEGOÑA PRADOS RODRIGUEZ", "117"],
    ["Vestuario Femenino Planta Alta", "CARMEN LIANA RUSU", "118"],
    ["Vestuario Femenino Planta Alta", "BLANCA HENAR CUÑADO", "119"],
    ["Vestuario Femenino Planta Alta", "BEATRIZ PALOMAR", "120"],
    ["Vestuario Femenino Planta Alta", "CAROLINA GARCIA CARO", "121"],
    ["Vestuario Femenino Planta Alta", "CRISTINA JIMENEZ GARCIA", "122"],
    ["Vestuario Femenino Planta Alta", "CRISTINA DIAZ DE LA CRUZ", "123"],
    ["Vestuario Femenino Planta Alta", "CRISTINA PRIETO GARCES", "124"],
    ["Vestuario Femenino Planta Alta", "CRISTINA MUÑOZ CASADO", "125"],
    ["Vestuario Femenino Planta Alta", "CRISTINA SANCHEZ ARGUELLES", "126"],
    ["Vestuario Femenino Planta Alta", "ADELA MARIN MORA", "127"],
    ["Vestuario Femenino Planta Alta", "SANDRA ORTEGA RIZO", "128"],
    ["Vestuario Femenino Planta Alta", "NEREA BACHILLER DE LARA", "129"],
    ["Vestuario Femenino Planta Alta", "ELENA MOLPECERES GUERRA", "130"],
    ["Vestuario Femenino Planta Alta", "DIANA JIMENEZ CRIADO", "131"],
    ["Vestuario Femenino Planta Alta", "ELSA ESCUDERO YUBERO", "132"],
    ["Vestuario Femenino Planta Alta", "DIANA REMESAL PEREZ", "133"],
    ["Vestuario Femenino Planta Alta", "LAURA MARTINEZ HERNANDO", "134"],
    ["Vestuario Femenino Planta Alta", "DOLORES CALDERON AGUILARES", "135"],
    ["Vestuario Femenino Planta Alta", "LAURA SAIZ VENTURA", "136"],
    ["Vestuario Femenino Planta Alta", "MARTA LOPEZ RIVILLA", "137"],
    ["Vestuario Femenino Planta Alta", "LAZARINA NIKOLAEVA MINKOVA", "138"],
    ["Vestuario Femenino Planta Alta", "EVA Mª MORALES OLIVA", "139"],
    ["Vestuario Femenino Planta Alta", "LETICIA BURGUILLOS BARRASA", "140"],
    ["Vestuario Femenino Planta Alta", "MARZENA GRAB DOROTA", "141"],
    ["Vestuario Femenino Planta Alta", "Mª ALMUDENA OCAÑA DIEGUEZ", "142"],
    ["Vestuario Femenino Planta Alta", "IDANIA FERNANDEZ LLANO", "143"],
    ["Vestuario Femenino Planta Alta", "Mª CARMEN AVILES SANTAMARIA", "144"],
    ["Vestuario Femenino Planta Alta", "LARA CASTELLANOS ROMERO", "145"],
    ["Vestuario Femenino Planta Alta", "Mª DEL PILAR SAYAGO PAVON", "146"],
    ["Vestuario Femenino Planta Alta", "LARA SILVA OJEDA", "147"],
    ["Vestuario Femenino Planta Alta", "LAURA DURAN ORTEGA", "148"],
    ["Vestuario Femenino Planta Alta", "NEREA SORIA LOPEZ", "149"],
    ["Vestuario Femenino Planta Alta", "Mª MAR MARTINEZ VILLAMAYOR", "150"],
    ["Vestuario Femenino Planta Alta", "LAURA ESQUIVEL RODRIGUEZ", "151"],
    ["Vestuario Femenino Planta Alta", "Mª TERESA MORALES DELGADO", "152"],
    ["Vestuario Femenino Planta Alta", "LIDIA RODRIGUEZ GONZALEZ", "153"],
    ["Vestuario Femenino Planta Alta", "MANUELA ALVEZ CANO", "154"],
    ["Vestuario Femenino Planta Alta", "Mª ANGELES ESCALONA SANCHEZ", "155"],
    ["Vestuario Femenino Planta Alta", "MONICA GORDILLO HERRERO", "156"],
    ["Vestuario Femenino Planta Alta", "Mª ANGELES FUENSANTA", "157"],
    ["Vestuario Femenino Planta Alta", "MARIA CARMEN GARRIDO RAYO", "158"],
    ["Vestuario Femenino Planta Alta", "Mª ANTONIA HERNANDEZ SANCHEZ", "159"],
    ["Vestuario Femenino Planta Alta", "EVA MARTIN MARTIN", "160"],
    ["Vestuario Femenino Planta Alta", "DIANA CAROLINA MEJIA ALCALDE", "161"],
    ["Vestuario Femenino Planta Alta", "YURI YAMILETH GONZALEZ", "162"],
    ["Vestuario Femenino Planta Alta", "MARIA JOSE PRADO", "163"],
    ["Vestuario Femenino Planta Alta", "MARIA DO CARMO FERREIRA GONCALVES", "164"],
    ["Vestuario Femenino Planta Alta", "Mª JOSE MARTINEZ PAMPANAS", "165"],
    ["Vestuario Femenino Planta Alta", "MARIA ISABEL AGUADO CASTILLA", "166"],
    ["Vestuario Femenino Planta Alta", "SILVIA MARTINEZ CANTERO", "167"],
    ["Vestuario Femenino Planta Alta", "MARIA SILVIA ROSA MATEO", "168"],
    ["Vestuario Femenino Planta Alta", "MªDOLORES MORALES LUQUE", "169"],
    ["Vestuario Femenino Planta Alta", "MARIA TERESA DE MIGUEL OLIVARES", "170"],
    ["Vestuario Femenino Planta Alta", "LIZZA PAIVA", "171"],
    ["Vestuario Femenino Planta Alta", "Alicia Romero", "172"],
    ["Vestuario Femenino Planta Alta", "MARIA DEL MAR MORENO GOMEZ", "173"],
    ["Vestuario Femenino Planta Alta", "MONICA SALOR SANCHEZ", "174"],
    ["Vestuario Femenino Planta Alta", "SONIA RUIZ RODRIGUEZ", "175"],
    ["Vestuario Femenino Planta Alta", "ALBA SILVA GOMEZ", "176"],
    ["Vestuario Femenino Planta Alta", "SILVIYA BOGOMILOVA BOGDANOVA", "177"],
    ["Vestuario Femenino Planta Alta", "NOELIA HIGUERAS GUTIERREZ", "178"],
    ["Vestuario Femenino Planta Alta", "MELISA ROMERO MORENO", "179"],
    ["Vestuario Femenino Planta Alta", "PALOMA CARMENO CALDERON", "180"],
    ["Vestuario Femenino Planta Alta", "MILENA VALENTINOVA SPIROVA", "181"],
    ["Vestuario Femenino Planta Alta", "PALOMA LIZANA HERRAIZ", "182"],
    ["Vestuario Femenino Planta Alta", "NOELIA VILLALBA", "183"],
    ["Vestuario Femenino Planta Alta", "MARTHA MANJARRÉS", "184"],
    ["Vestuario Femenino Planta Alta", "LAURA DEL VALLE RODRIGUEZ QUIJADA", "185"],
    ["Vestuario Femenino Planta Alta", "RAQUEL CARBAJO PEREZ", "186"],
    ["Vestuario Femenino Planta Alta", "Mª GEMA TORREJON MUÑOZ", "187"],
    ["Vestuario Femenino Planta Alta", "ROCIO FERNANDEZ GARRIDO", "188"],
    ["Vestuario Femenino Planta Alta", "TAMARA LAOSSA REYES", "189"],
    ["Vestuario Femenino Planta Alta", "ROSA LOPEZ FERNANDEZ", "190"],
    ["Vestuario Femenino Planta Alta", "Mª CARMEN GARCIA JIMENEZ", "191"],
    ["Vestuario Femenino Planta Alta", "ROSA Mª OLIVA GRANADO", "192"],
    ["Vestuario Femenino Planta Alta", "ANA FEIDT", "193"],
    ["Vestuario Femenino Planta Alta", "SILVIA DIAZ PEREZ", "194"],
    ["Vestuario Femenino Planta Alta", "NURIA DEL RIO SANCHEZ", "195"],
    ["Vestuario Femenino Planta Alta", "SILVIA ISIDRO PONTERO", "196"],
    ["Vestuario Femenino Planta Alta", "JELEN LORENA QUIÑONES", "197"],
    ["Vestuario Femenino Planta Alta", "SONIA BLANCO ARROYO", "198"],
    ["Vestuario Femenino Planta Alta", "ALBA GARCIA AGUILERA", "199"],
    ["Vestuario Femenino Planta Alta", "ANA MERCEDES TREJOS", "200"],
    ["Vestuario Femenino Planta Alta", "PALOMA ESPARTOSA DE LUCAS", "201"],
    ["Vestuario Femenino Planta Alta", "SONIA URDILLO LUENGO", "202"],
    ["Vestuario Femenino Planta Alta", "ROCIO GARCIA FERNANDEZ", "203"],
    ["Vestuario Femenino Planta Alta", "JUDIT MONTERO JORDI", "204"],
    ["Vestuario Femenino Planta Alta", "ROSA PORTALATIN CHAMORRO", "205"],
    ["Vestuario Femenino Planta Alta", "VIRGINIA ALCON BARRIGA", "206"],
    ["Vestuario Femenino Planta Alta", "Rocío Millán Ortiz", "207"],
    ["Vestuario Femenino Planta Alta", "ZAHIRA ALONSO ANTOLIN", "208"],
    ["Vestuario Femenino Planta Alta", "LAURA NAVARRO TORRES", "209"],
    ["Vestuario Femenino Planta Alta", "ANGELES HURTADO AVILA", "210"],
    ["Vestuario Femenino Planta Alta", "SUSANA DIAZ BRAVO", "211"],
    ["Vestuario Femenino Planta Alta", "VANESSA PESCADOR GARCIA", "212"],
    ["Vestuario Femenino Planta Alta", "TAMARA RAMIRO TORRES", "213"],
    ["Vestuario Femenino Planta Alta", "DOLORES ESTHER VIDAL MTZ", "214"],
    ["Vestuario Femenino Planta Alta", "VERONICA BECERRA PALMA", "215"],
    ["Vestuario Femenino Planta Alta", "FÁTIMA EZZAHRAE", "216"],
    ["Vestuario Femenino Planta Alta", "VERONICA FERNANDEZ RAMOS", "217"],
    ["Vestuario Femenino Planta Alta", "PAULA CANOREA", "218"],
    ["Vestuario Femenino Planta Alta", "YIRLEIDIS KATHERIN LEMOS", "219"],
    ["Vestuario Femenino Planta Alta", "Mª CARMEN ACEBEDA ELIPE", "220"],
    ["Vestuario Femenino Planta Alta", "YOLANDA GONZALEZ COLINA", "221"],
    ["Vestuario Femenino Planta Alta", "MONTSERAT PANIAGUA BARRIGA", "222"],
    ["Vestuario Femenino Planta Alta", "YOLANDA RUBIO ROMAN", "223"],
    ["Vestuario Femenino Planta Alta", "YESLIN ROMELIA MONTILLA MOWAZ", "224"],
    ["Vestuario Femenino Planta Alta", "Mª ISABEL NEVADO CARRILLO", "225"],
    ["Vestuario Femenino Planta Alta", "SARA MARTINEZ UTIEL", "226"],
    ["Vestuario Femenino Planta Alta", "SUSANA ALCAIDE", "227"],
    ["Vestuario Femenino Planta Alta", "ANA Mª GONZALEZ MUÑOZ", "228"],
    ["Vestuario Femenino Planta Alta", "HERMINIA LOPRESTI PERAL", "229"],
    ["Vestuario Femenino Planta Alta", "DANIELA ANCUTA PRODAN", "230"],
    ["Vestuario Femenino Planta Alta", "AURINELLYS DEL VALLE CARMONA", "231"],
    ["Vestuario Femenino Planta Alta", "ELENA NUÑEZ UTRILLA", "232"],
    ["Vestuario Femenino Planta Alta", "SARA RUBIO ALVAREZ", "233"],
    ["Vestuario Femenino Planta Alta", "YAIZA SANJUAN BLANCO", "235"],
    ["Vestuario Femenino Planta Alta", "ESTELA CABRERA", "236"],
    ["Vestuario Femenino Planta Alta", "SANDRA ALCÁNTARA", "237"],
    ["Vestuario Femenino Planta Alta", "ROSIANE CAMARA RUESGA DEL REY", "238"],
    ["Vestuario Femenino Planta Alta", "PATRICIA MOLPECERES", "239"],
    ["Vestuario Femenino Planta Alta", "SARA GARCIA MARTINEZ", "240"],
    ["Vestuario Femenino Planta Alta", "Alba Sinobas Zamorano", "241"],
    ["Vestuario Femenino Planta Alta", "NURIA SANCHEZ MARTIN", "242"],
    ["Vestuario Femenino Planta Alta", "DOLORES ARROYO RODRIGEZ", "243"],
    ["Vestuario Femenino Planta Alta", "CASTI GARCIA HERNANDEZ", "244"],
    ["Vestuario Femenino Planta Alta", "YOLANDA GUTIERREZ PALACIOS", "245"],
    ["Vestuario Femenino Planta Alta", "TAMARA SANCHEZ GOMEZ", "246"],
    ["Vestuario Femenino Planta Alta", "MONICA DIVASTO", "247"],
    ["Vestuario Femenino Planta Alta", "JESSICA VELASCO", "248"],
    ["Vestuario Femenino Planta Alta", "Mª NIEVES ALCANTARA", "249"],
    ["Vestuario Femenino Planta Alta", "LESLIE GIOVANNA ANLAS MARTINEZ", "250"],
    ["Vestuario Femenino Planta Alta", "RAQUEL DEL PILAR CONTY", "251"],
    ["Vestuario Femenino Planta Alta", "SANTA MONICA PEREZ", "252"],
    ["Vestuario Femenino Planta Alta", "ALINA ZANFIR", "253"],
    ["Vestuario Femenino Planta Alta", "MARALIS ALMEIDA PEREZ", "254"],
    ["Vestuario Femenino Planta Alta", "ISVIC URDANETA", "255"],
    ["Vestuario Femenino Planta Alta", "ANA MARIA ZAFRA", "256"],
    ["Vestuario Femenino Planta Alta", "NEREA JIMENEZ RODRIGUEZ", "257"],
    ["Vestuario Femenino Planta Alta", "JACKLIN CAROLINA GARCIA", "258"],
    ["Vestuario Femenino Planta Alta", "KATTHERINE GABRIELA ARAUCO", "260"],
    ["Vestuario Femenino Planta Alta", "NURIA SANCHEZ PRADOS", "261"],
    ["Vestuario Femenino Planta Alta", "VERA DANUTA", "262"],
    ["Vestuario Femenino Planta Alta", "SILVIA CORONADO DELAOSA", "263"],
    ["Vestuario Masculino Planta Baja", "JUAN JOSE RODRIGUEZ", "2"],
    ["Vestuario Masculino Planta Baja", "MIHAI RUNCEANU", "3"],
    ["Vestuario Masculino Planta Baja", "MIGUEL SERRANO", "4"],
    ["Vestuario Masculino Planta Baja", "ANGEL MOLPECERES", "5"],
    ["Vestuario Masculino Planta Baja", "ENRIQUE MARTINEZ LOPEZ", "6"],
    ["Vestuario Masculino Planta Baja", "DANIEL PETRESCU", "7"],
    ["Vestuario Masculino Planta Baja", "MARCELO GRIGORAS", "8"],
    ["Vestuario Masculino Planta Baja", "DANIEL GIURGIO", "9"],
    ["Vestuario Masculino Planta Baja", "CARLOS APARICIO OLMEDO", "10"],
    ["Vestuario Masculino Planta Baja", "JAVIER CARRETERO", "12"],
    ["Vestuario Masculino Planta Baja", "CARLOS SANTANAMARIA", "13"],
    ["Vestuario Masculino Planta Baja", "RAUL SANTANA", "14"],
    ["Vestuario Masculino Planta Baja", "BORJA CRESPO", "15"],
    ["Vestuario Masculino Planta Baja", "JOSE LUIS GIL", "16"],
    ["Vestuario Masculino Planta Baja", "JESUS VALDERRAMA", "17"],
    ["Vestuario Masculino Planta Baja", "IKER SANCHEZ", "18"],
    ["Vestuario Masculino Planta Baja", "JUAN FRANCISCO PEREZ ARENA", "19"],
    ["Vestuario Masculino Planta Baja", "JOSE", "20"],
    ["Vestuario Masculino Planta Baja", "ALEXEI MENENDEZ", "121"],
    ["Vestuario Masculino Planta Baja", "JOSE RAMIREZ ARANDA", "122"],
    ["Vestuario Masculino Planta Baja", "ARMANDO JOSE DE OLIVEIRA", "123"],
    ["Vestuario Masculino Planta Baja", "ANGEL CASTAÑO", "124"],
    ["Vestuario Masculino Planta Baja", "MIGUEL ANGEL RODRIGUEZ", "125"],
    ["Vestuario Masculino Planta Baja", "JORGE LOZANO", "126"],
    ["Vestuario Masculino Planta Baja", "PABLO MECANICO", "127"],
    ["Vestuario Masculino Planta Baja", "FLORENCIO ZAFRA LOPESINO", "128"]
  ];

  const employees = await base44.entities.Employee.list();
  const lockerAssignments = await base44.entities.LockerAssignment.list();

  const normalizeString = (str) => {
    if (!str) return "";
    return str
      .toUpperCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^A-Z0-9]/g, "");
  };

  const results = {
    matched: 0,
    notFound: [],
    updated: []
  };

  for (const [vestuario, employeeName, lockerNumber] of lockerData) {
    if (!employeeName || employeeName.trim() === "") continue;

    const normalizedSearch = normalizeString(employeeName);
    const employee = employees.find(emp => 
      normalizeString(emp.nombre) === normalizedSearch
    );

    if (!employee) {
      results.notFound.push(employeeName);
      continue;
    }

    const existingAssignment = lockerAssignments.find(la => la.employee_id === employee.id);

    const assignmentData = {
      employee_id: employee.id,
      requiere_taquilla: true,
      vestuario: vestuario,
      numero_taquilla_actual: lockerNumber,
      numero_taquilla_nuevo: null,
      fecha_asignacion: new Date().toISOString(),
      notificacion_enviada: false
    };

    if (existingAssignment) {
      await base44.entities.LockerAssignment.update(existingAssignment.id, assignmentData);
    } else {
      await base44.entities.LockerAssignment.create(assignmentData);
    }

    results.matched++;
    results.updated.push(`${employee.nombre} -> ${vestuario} #${lockerNumber}`);
  }

  return results;
}